# syntax = docker/dockerfile:1.2
FROM python:3.9-alpine3.12

RUN apk add --no-cache aws-cli

# Install Pacu
WORKDIR /usr/src/marionette/
ENV PYTHONPATH /usr/src/marionette/

# Install dev requirements
RUN --mount=type=cache,target=/var/cache/apk apk add \
    gcc \
    build-base \
    musl-dev \
    linux-headers \
    libffi-dev \
    openssl-dev \
    rust \
    cargo \
    make \
    bash

RUN --mount=type=cache,target=/root/.cache/pip python -m pip install --upgrade pip
RUN --mount=type=cache,target=/root/.cache/pip pip install poetry

COPY ./ ./
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

ENTRYPOINT ["bash", "-c"]
CMD ["bash"]
